package com.moneyweather.model.enums

enum class ServerResponseCodeEnum {
    SUCCESS            /*  0 */,
    EXCEPTION          /*  1 */,
    NOT_REGISTERED     /*  2 */,
    MISSING_PARAMS     /*  3 */,
    INVALID_PARAMS     /*  4 */,
    INVALID_USER_INFO  /*  5 */,
    INVALID_TOKEN_TYPE /*  6 */,
    SNSID_EXISTED      /*  7 */,
    INVALID_EMAIL      /*  8 */,
    EMAIL_EXISTED      /*  9 */,
    PHONE_EXISTED      /* 10 */,
    INVALID_NAME       /* 11 */,
    INVALID_NICKNAME   /* 12 */,
    NICKNAME_EXISTED   /* 13 */,
    INVALID_BIRTHDAY   /* 14 */,
    INVALID_SEX_VALUE  /* 15 */,
    ACCESS_DENIED      /* 16 */,
    SEND_MESSAGE_FAILED/* 17 */,
    INVALID_CONFIRM_CODE/* 18 */,
    INVALID_SMS_CODE/* 19 */,
    NOT_MATCH /* 20 */,
    TIMEOUT /* 21 */,
    DATA_NOTFOUND /* 22 */,
    SEND_MESSAGE_EXCEPTION /* 23 */,
    UPLOAD_TOO_MUCH /* 24 */,
    USER_ID_INVALID /* 25 */,
    USER_NOTFOUND /* 26 */,
    USER_ID_AND_JWT_NOT_MATCH /* 27 */,
    INVALID_QUESTION_CONTENT /* 28 */,
    INVALID_QUESTION_TYPE /* 29 */,
    NOT_IMAGE_FILE /* 30 */,
    TICKET_NUMBER_INVALID /* 31 */,
    REFUND_BANK_NAME_EMPTY /* 32 */,
    REFUND_BANK_ACCOUNT_EMPTY /* 33 */,
    REFUND_ACCOUNT_NAME_EMPTY /* 34 */,
    REFUND_ATTACH_IMAGE_EMPTY /* 35 */,
    REFUND_ATTACH_IMAGE_NOTFOUND /* 36 */,
    TICKET_NUMBER_EXCHANGE_INVALID /* 37 */,
    INVALID_BRANCH_ID /* 38 */,
    FAVORITE_ALREADY_ADDED /* 39 */,
    EVENT_ALREADY_ADDED /* 40 */,
    ORDER_QUANTITY_INVALID /* 41 */,
    ORDER_FOOD_BRANCH_NOT_MATCH /* 42 */,
    ORDER_FOOD_STATUS_INVALID /* 43 */,
    ORDER_FOOD_NOT_FOUND /* 44 */,
    INVALID_ORDER_COUPON_NUMBER /* 45 */,
    COMMUNITY_COMMENT_CONTENT_EMPTY /* 46 */,
    COMMUNITY_COMMENT_NOT_FOUND /* 47 */,
    COMMUNITY_COMMENT_DELETED /* 48 */,
    COMMUNITY_ID_INVALID /* 49 */,
    COMMUNITY_NOT_FOUND /* 50 */,
    ORDER_FOOD_LIST_EMPTY /* 51 */,
    FRIEND_SEARCH_EMPTY /* 52 */,
    FRIEND_ALREADY_BE_FRIEND /* 53 */,
    POINT_COUPON_NUMBER_INVALID /* 54 */,
    POINT_COUPON_NUMBER_NOTENOUGH /* 55 */,
    ;

    companion object {
        fun parserToEnum(value: Int): ServerResponseCodeEnum {
            return values()[value]
        }
    }
}